trigger:
- main
pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build -- configuration $(buidConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'